package ai_gateway

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/pradigi/backend/internal/core/kernel"
	"github.com/pradigi/backend/internal/core/mission_compiler"
	"github.com/pradigi/backend/internal/core/mission_engine"
	"github.com/pradigi/backend/internal/pkg/logger"
)

// RichMissionContext provides the LLM with pre-assembled learner state without database queries.
type RichMissionContext struct {
	PreviousAttempts    int      `json:"previous_attempts"`
	KnownCapabilities   []string `json:"known_capabilities"`
	MissingCapabilities []string `json:"missing_capabilities"`
	LearningStyle       string   `json:"learning_style"`
	ExecutionIntent     string   `json:"execution_intent"`
}

// RichMissionInstance is the contextualized output generated by AI Gateway.
type RichMissionInstance struct {
	InstanceID          string                                 `json:"instance_id"`
	GoalID              string                                 `json:"goal_id"`
	Title               string                                 `json:"title"`
	Objective           string                                 `json:"objective"`
	Context             RichMissionContext                     `json:"context"`
	RuntimeRequirements mission_compiler.RuntimeRequirements `json:"runtime_requirements"`
	SeedFiles           map[string]string                      `json:"seed_files"`
	EvaluationRules     []string                               `json:"evaluation_rules"`
}

// Gateway acts as the decoupled AI process subscribing to OS Scheduler requests.
// BOUNDARY RULE: AI Gateway encapsulates prompt building and LLM adapters. The OS Scheduler never sees this.
type Gateway struct {
	bus kernel.EventBus
}

func NewGateway(bus kernel.EventBus) *Gateway {
	return &Gateway{bus: bus}
}

// OnEvent subscribes to EventMissionRequested emitted by the OS Scheduler.
func (g *Gateway) OnEvent(ctx context.Context, event kernel.Event) error {
	if event.Type != mission_engine.EventMissionRequested {
		return nil
	}

	var spec mission_compiler.MissionSpecification
	if err := json.Unmarshal(event.Payload, &spec); err != nil {
		return fmt.Errorf("failed to unmarshal specification in AI Gateway: %w", err)
	}

	logger.Info().Str("session", event.SessionID).Str("mission", spec.MissionID).Msg("AI Gateway executing Context Builder & Prompt Builder")

	// 1. Context Builder (Pre-assembled Learner State)
	mContext := RichMissionContext{
		PreviousAttempts:    1,
		KnownCapabilities:   []string{"http_headers", "bearer_token"},
		MissingCapabilities: []string{"jwt_expiration", "signature_verification"},
		LearningStyle:       "adaptive_scaffolded",
		ExecutionIntent:     "production_grade_security",
	}

	// 2. Prompt Builder & Model Adapter (Agnostic to GPT/Claude/Gemini/Pradigi-1)
	// In production, this invokes the active LLM adapter. Here we generate deterministic rich instance.
	instance := &RichMissionInstance{
		InstanceID:          fmt.Sprintf("inst_%d", time.Now().Unix()),
		GoalID:              spec.GoalID,
		Title:               "Implement production-grade JWT expiration validation",
		Objective:           spec.Objective,
		Context:             mContext,
		RuntimeRequirements: spec.RuntimeRequirements,
		SeedFiles: map[string]string{
			"auth_middleware.go": "package middleware\n\n// TODO: Implement JWT expiration check\n",
		},
		EvaluationRules: spec.EvaluationRules,
	}

	// 3. Emit EventMissionGenerated to OS Event Bus
	payloadBytes, _ := json.Marshal(instance)
	genEvent := kernel.Event{
		ID:        fmt.Sprintf("evt_gen_%d", time.Now().UnixNano()),
		SessionID: event.SessionID,
		Type:      mission_engine.EventMissionGenerated,
		Source:    "ai_gateway_process",
		Timestamp: time.Now(),
		Payload:   payloadBytes,
	}

	logger.Info().Str("session", event.SessionID).Msg("AI Gateway emitting MissionGenerated event to OS Event Bus")
	return g.bus.Publish(ctx, genEvent)
}
