CREATE TABLE IF NOT EXISTS provinces (
    id         VARCHAR(20) PRIMARY KEY,
    country_id VARCHAR(2) NOT NULL REFERENCES countries(id),
    name       VARCHAR(200) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_provinces_country_id ON provinces(country_id);

INSERT INTO provinces (id, country_id, name) VALUES
    ('11', 'ID', 'ACEH'),
    ('12', 'ID', 'SUMATERA UTARA'),
    ('13', 'ID', 'SUMATERA BARAT'),
    ('14', 'ID', 'RIAU'),
    ('15', 'ID', 'JAMBI'),
    ('16', 'ID', 'SUMATERA SELATAN'),
    ('17', 'ID', 'BENGKULU'),
    ('18', 'ID', 'LAMPUNG'),
    ('19', 'ID', 'KEPULAUAN BANGKA BELITUNG'),
    ('21', 'ID', 'KEPULAUAN RIAU'),
    ('31', 'ID', 'DKI JAKARTA'),
    ('32', 'ID', 'JAWA BARAT'),
    ('33', 'ID', 'JAWA TENGAH'),
    ('34', 'ID', 'DI YOGYAKARTA'),
    ('35', 'ID', 'JAWA TIMUR'),
    ('36', 'ID', 'BANTEN'),
    ('51', 'ID', 'BALI'),
    ('52', 'ID', 'NUSA TENGGARA BARAT'),
    ('53', 'ID', 'NUSA TENGGARA TIMUR'),
    ('61', 'ID', 'KALIMANTAN BARAT'),
    ('62', 'ID', 'KALIMANTAN TENGAH'),
    ('63', 'ID', 'KALIMANTAN SELATAN'),
    ('64', 'ID', 'KALIMANTAN TIMUR'),
    ('65', 'ID', 'KALIMANTAN UTARA'),
    ('71', 'ID', 'SULAWESI UTARA'),
    ('72', 'ID', 'SULAWESI TENGAH'),
    ('73', 'ID', 'SULAWESI SELATAN'),
    ('74', 'ID', 'SULAWESI TENGGARA'),
    ('75', 'ID', 'GORONTALO'),
    ('76', 'ID', 'SULAWESI BARAT'),
    ('81', 'ID', 'MALUKU'),
    ('82', 'ID', 'MALUKU UTARA'),
    ('91', 'ID', 'PAPUA BARAT'),
    ('94', 'ID', 'PAPUA'),

    ('US-AL', 'US', 'Alabama'),
    ('US-AK', 'US', 'Alaska'),
    ('US-AZ', 'US', 'Arizona'),
    ('US-AR', 'US', 'Arkansas'),
    ('US-CA', 'US', 'California'),
    ('US-CO', 'US', 'Colorado'),
    ('US-CT', 'US', 'Connecticut'),
    ('US-DE', 'US', 'Delaware'),
    ('US-FL', 'US', 'Florida'),
    ('US-GA', 'US', 'Georgia'),
    ('US-HI', 'US', 'Hawaii'),
    ('US-ID', 'US', 'Idaho'),
    ('US-IL', 'US', 'Illinois'),
    ('US-IN', 'US', 'Indiana'),
    ('US-IA', 'US', 'Iowa'),
    ('US-KS', 'US', 'Kansas'),
    ('US-KY', 'US', 'Kentucky'),
    ('US-LA', 'US', 'Louisiana'),
    ('US-ME', 'US', 'Maine'),
    ('US-MD', 'US', 'Maryland'),
    ('US-MA', 'US', 'Massachusetts'),
    ('US-MI', 'US', 'Michigan'),
    ('US-MN', 'US', 'Minnesota'),
    ('US-MS', 'US', 'Mississippi'),
    ('US-MO', 'US', 'Missouri'),
    ('US-MT', 'US', 'Montana'),
    ('US-NE', 'US', 'Nebraska'),
    ('US-NV', 'US', 'Nevada'),
    ('US-NH', 'US', 'New Hampshire'),
    ('US-NJ', 'US', 'New Jersey'),
    ('US-NM', 'US', 'New Mexico'),
    ('US-NY', 'US', 'New York'),
    ('US-NC', 'US', 'North Carolina'),
    ('US-ND', 'US', 'North Dakota'),
    ('US-OH', 'US', 'Ohio'),
    ('US-OK', 'US', 'Oklahoma'),
    ('US-OR', 'US', 'Oregon'),
    ('US-PA', 'US', 'Pennsylvania'),
    ('US-RI', 'US', 'Rhode Island'),
    ('US-SC', 'US', 'South Carolina'),
    ('US-SD', 'US', 'South Dakota'),
    ('US-TN', 'US', 'Tennessee'),
    ('US-TX', 'US', 'Texas'),
    ('US-UT', 'US', 'Utah'),
    ('US-VT', 'US', 'Vermont'),
    ('US-VA', 'US', 'Virginia'),
    ('US-WA', 'US', 'Washington'),
    ('US-WV', 'US', 'West Virginia'),
    ('US-WI', 'US', 'Wisconsin'),
    ('US-WY', 'US', 'Wyoming'),
    ('US-DC', 'US', 'District of Columbia'),

    ('SG-01', 'SG', 'Central Singapore'),
    ('SG-02', 'SG', 'North East'),
    ('SG-03', 'SG', 'North West'),
    ('SG-04', 'SG', 'South East'),
    ('SG-05', 'SG', 'South West'),

    ('MY-01', 'MY', 'Johor'),
    ('MY-02', 'MY', 'Kedah'),
    ('MY-03', 'MY', 'Kelantan'),
    ('MY-04', 'MY', 'Melaka'),
    ('MY-05', 'MY', 'Negeri Sembilan'),
    ('MY-06', 'MY', 'Pahang'),
    ('MY-07', 'MY', 'Pulau Pinang'),
    ('MY-08', 'MY', 'Perak'),
    ('MY-09', 'MY', 'Perlis'),
    ('MY-10', 'MY', 'Selangor'),
    ('MY-11', 'MY', 'Terengganu'),
    ('MY-12', 'MY', 'Sabah'),
    ('MY-13', 'MY', 'Sarawak'),
    ('MY-14', 'MY', 'Kuala Lumpur'),
    ('MY-15', 'MY', 'Labuan'),
    ('MY-16', 'MY', 'Putrajaya'),

    ('TH-10', 'TH', 'Bangkok'),
    ('TH-11', 'TH', 'Samut Prakan'),
    ('TH-12', 'TH', 'Nonthaburi'),
    ('TH-13', 'TH', 'Pathum Thani'),
    ('TH-14', 'TH', 'Phra Nakhon Si Ayutthaya'),
    ('TH-15', 'TH', 'Ang Thong'),
    ('TH-20', 'TH', 'Chon Buri'),
    ('TH-21', 'TH', 'Rayong'),
    ('TH-22', 'TH', 'Chanthaburi'),
    ('TH-23', 'TH', 'Trat'),
    ('TH-30', 'TH', 'Nakhon Ratchasima'),
    ('TH-40', 'TH', 'Khon Kaen'),
    ('TH-50', 'TH', 'Chiang Mai'),
    ('TH-51', 'TH', 'Lamphun'),
    ('TH-52', 'TH', 'Lampang'),
    ('TH-53', 'TH', 'Uttaradit'),
    ('TH-54', 'TH', 'Phrae'),
    ('TH-55', 'TH', 'Nan'),
    ('TH-56', 'TH', 'Phayao'),
    ('TH-57', 'TH', 'Chiang Rai'),
    ('TH-58', 'TH', 'Mae Hong Son'),
    ('TH-60', 'TH', 'Nakhon Sawan'),
    ('TH-70', 'TH', 'Ratchaburi'),
    ('TH-71', 'TH', 'Kanchanaburi'),
    ('TH-72', 'TH', 'Suphan Buri'),
    ('TH-73', 'TH', 'Nakhon Pathom'),
    ('TH-80', 'TH', 'Nakhon Si Thammarat'),
    ('TH-81', 'TH', 'Krabi'),
    ('TH-82', 'TH', 'Phang Nga'),
    ('TH-83', 'TH', 'Phuket'),
    ('TH-84', 'TH', 'Surat Thani'),
    ('TH-90', 'TH', 'Songkhla'),
    ('TH-91', 'TH', 'Satun'),
    ('TH-92', 'TH', 'Trang'),
    ('TH-93', 'TH', 'Phatthalung'),
    ('TH-94', 'TH', 'Pattani'),
    ('TH-95', 'TH', 'Yala'),
    ('TH-96', 'TH', 'Narathiwat'),

    ('PH-00', 'PH', 'National Capital Region (NCR)'),
    ('PH-01', 'PH', 'Ilocos Region (Region I)'),
    ('PH-02', 'PH', 'Cagayan Valley (Region II)'),
    ('PH-03', 'PH', 'Central Luzon (Region III)'),
    ('PH-04', 'PH', 'CALABARZON (Region IV-A)'),
    ('PH-05', 'PH', 'Bicol Region (Region V)'),
    ('PH-06', 'PH', 'Western Visayas (Region VI)'),
    ('PH-07', 'PH', 'Central Visayas (Region VII)'),
    ('PH-08', 'PH', 'Eastern Visayas (Region VIII)'),
    ('PH-09', 'PH', 'Zamboanga Peninsula (Region IX)'),
    ('PH-10', 'PH', 'Northern Mindanao (Region X)'),
    ('PH-11', 'PH', 'Davao Region (Region XI)'),
    ('PH-12', 'PH', 'SOCCSKSARGEN (Region XII)'),
    ('PH-13', 'PH', 'Caraga (Region XIII)'),
    ('PH-14', 'PH', 'Cordillera Administrative Region (CAR)'),
    ('PH-15', 'PH', 'Bangsamoro (BARMM)'),
    ('PH-16', 'PH', 'MIMAROPA'),

    ('VN-01', 'VN', 'Lai Chau'),
    ('VN-02', 'VN', 'Lao Cai'),
    ('VN-03', 'VN', 'Ha Giang'),
    ('VN-04', 'VN', 'Cao Bang'),
    ('VN-05', 'VN', 'Son La'),
    ('VN-06', 'VN', 'Yen Bai'),
    ('VN-07', 'VN', 'Tuyen Quang'),
    ('VN-08', 'VN', 'Lang Son'),
    ('VN-09', 'VN', 'Quang Ninh'),
    ('VN-10', 'VN', 'Hoa Binh'),
    ('VN-11', 'VN', 'Ha Noi'),
    ('VN-12', 'VN', 'Hai Phong'),
    ('VN-13', 'VN', 'Nam Dinh'),
    ('VN-14', 'VN', 'Thai Binh'),
    ('VN-15', 'VN', 'Ninh Binh'),
    ('VN-16', 'VN', 'Thanh Hoa'),
    ('VN-17', 'VN', 'Nghe An'),
    ('VN-18', 'VN', 'Ha Tinh'),
    ('VN-19', 'VN', 'Quang Binh'),
    ('VN-20', 'VN', 'Quang Tri'),
    ('VN-21', 'VN', 'Thua Thien Hue'),
    ('VN-22', 'VN', 'Da Nang'),
    ('VN-23', 'VN', 'Quang Nam'),
    ('VN-24', 'VN', 'Quang Ngai'),
    ('VN-25', 'VN', 'Binh Dinh'),
    ('VN-26', 'VN', 'Phu Yen'),
    ('VN-27', 'VN', 'Khanh Hoa'),
    ('VN-28', 'VN', 'Ninh Thuan'),
    ('VN-29', 'VN', 'Binh Thuan'),
    ('VN-30', 'VN', 'Kon Tum'),
    ('VN-31', 'VN', 'Gia Lai'),
    ('VN-32', 'VN', 'Dak Lak'),
    ('VN-33', 'VN', 'Dak Nong'),
    ('VN-34', 'VN', 'Lam Dong'),
    ('VN-40', 'VN', 'Ho Chi Minh City'),
    ('VN-41', 'VN', 'Dong Nai'),
    ('VN-42', 'VN', 'Ba Ria - Vung Tau'),
    ('VN-43', 'VN', 'Binh Duong'),
    ('VN-44', 'VN', 'Tay Ninh'),
    ('VN-45', 'VN', 'Binh Phuoc'),
    ('VN-46', 'VN', 'Long An'),
    ('VN-47', 'VN', 'Tien Giang'),
    ('VN-48', 'VN', 'Ben Tre'),
    ('VN-49', 'VN', 'Tra Vinh'),
    ('VN-50', 'VN', 'Vinh Long'),
    ('VN-51', 'VN', 'Dong Thap'),
    ('VN-52', 'VN', 'An Giang'),
    ('VN-53', 'VN', 'Kien Giang'),
    ('VN-54', 'VN', 'Can Tho'),
    ('VN-55', 'VN', 'Hau Giang'),
    ('VN-56', 'VN', 'Soc Trang'),
    ('VN-57', 'VN', 'Bac Lieu'),
    ('VN-58', 'VN', 'Ca Mau'),
    ('VN-59', 'VN', 'Bac Giang'),
    ('VN-60', 'VN', 'Bac Kan'),

    ('GB-ENG', 'GB', 'England'),
    ('GB-SCT', 'GB', 'Scotland'),
    ('GB-WLS', 'GB', 'Wales'),
    ('GB-NIR', 'GB', 'Northern Ireland')
ON CONFLICT (id) DO NOTHING;
