import '../../../core/domain/models/mission_model.dart';
import 'incident_model.dart';
import 'evidence_model.dart';

abstract class MissionRepository {
  /// Fetches the daily mission generated by the AI for the current user
  Future<MissionModel?> getTodayMission();

  /// Gets the incident context that triggered the mission
  Future<IncidentModel> getIncident(String incidentId);

  /// Gets all evidence payloads attached to a specific mission
  Future<List<EvidenceModel>> getEvidenceForMission(String missionId);
}
